require 'ffi'
require 'gslng'
require 'hash_keyword_args'

require 'gsl-ng/matrix'
require 'sndfile/enums'
require 'sndfile/error'
require 'sndfile/sndfile_api'
require 'sndfile/info'
require 'sndfile/file'
